// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperCat.Routers.ChannelsRouter = (function(_super) {
    __extends(ChannelsRouter, _super);

    function ChannelsRouter() {
      return ChannelsRouter.__super__.constructor.apply(this, arguments);
    }

    ChannelsRouter.prototype.initialize = function(options) {
      this.channels = new SuperCat.Collections.ChannelsCollection();
      return this.channels.reset(options.channels);
    };

    ChannelsRouter.prototype.routes = {
      "new": "newChannel",
      "index": "index",
      ":id/edit": "edit",
      ":id": "show",
      ".*": "index"
    };

    ChannelsRouter.prototype.newChannel = function() {
      this.view = new SuperCat.Views.Channels.NewView({
        collection: this.channels
      });
      return $("#channels").html(this.view.render().el);
    };

    ChannelsRouter.prototype.index = function() {
      this.view = new SuperCat.Views.Channels.IndexView({
        channels: this.channels
      });
      return $("#channels").html(this.view.render().el);
    };

    ChannelsRouter.prototype.show = function(id) {
      var channel;
      channel = this.channels.get(id);
      this.view = new SuperCat.Views.Channels.ShowView({
        model: channel
      });
      return $("#channels").html(this.view.render().el);
    };

    ChannelsRouter.prototype.edit = function(id) {
      var channel;
      channel = this.channels.get(id);
      this.view = new SuperCat.Views.Channels.EditView({
        model: channel
      });
      return $("#channels").html(this.view.render().el);
    };

    return ChannelsRouter;

  })(Backbone.Router);

}).call(this);
