// Generated by CoffeeScript 1.7.1
(function() {
  var _base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (_base = SuperCat.Views).Channels || (_base.Channels = {});

  SuperCat.Views.Channels.ChannelView = (function(_super) {
    __extends(ChannelView, _super);

    function ChannelView() {
      return ChannelView.__super__.constructor.apply(this, arguments);
    }

    ChannelView.prototype.template = _.template(document.getElementById('channel').innerHTML);

    ChannelView.prototype.events = {
      "click .destroy": "destroy"
    };

    ChannelView.prototype.tagName = "tr";

    ChannelView.prototype.destroy = function() {
      this.model.destroy();
      this.remove();
      return false;
    };

    ChannelView.prototype.render = function() {
      $(this.el).html(this.template(this.model.toJSON()));
      return this;
    };

    return ChannelView;

  })(Backbone.View);

}).call(this);
