// Generated by CoffeeScript 1.7.1
(function() {
  var _base,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (_base = SuperCat.Views).Messages || (_base.Messages = {});

  SuperCat.Views.Messages.IndexView = (function(_super) {
    __extends(IndexView, _super);

    function IndexView() {
      this.render = __bind(this.render, this);
      this.addOne = __bind(this.addOne, this);
      this.addAll = __bind(this.addAll, this);
      return IndexView.__super__.constructor.apply(this, arguments);
    }

    IndexView.prototype.template = _.template(document.getElementById('message_index').innerHTML);

    IndexView.prototype.initialize = function(options) {
      this.options = new SuperCat.Collections.MessagesCollection;
      this.options.reset(options.messages);
      return this.options.messages.bind('reset', this.addAll);
    };

    IndexView.prototype.addAll = function() {
      return this.options.messages.each(this.addOne);
    };

    IndexView.prototype.addOne = function(message) {
      var view;
      view = new SuperCat.Views.Messages.MessageView({
        model: message
      });
      return this.$("tbody").append(view.render().el);
    };

    IndexView.prototype.render = function() {
      $(this.el).html(this.template({
        messages: this.options.messages.toJSON()
      }));
      this.addAll();
      return this;
    };

    return IndexView;

  })(Backbone.View);

}).call(this);
