// Generated by CoffeeScript 1.7.1
(function() {
  var _base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (_base = SuperCat.Views).Users || (_base.Users = {});

  SuperCat.Views.Users.UserView = (function(_super) {
    __extends(UserView, _super);

    function UserView() {
      return UserView.__super__.constructor.apply(this, arguments);
    }

    UserView.prototype.template = _.template(document.getElementById('user').innerHTML);

    UserView.prototype.events = {
      "click .destroy": "destroy"
    };

    UserView.prototype.tagName = "tr";

    UserView.prototype.destroy = function() {
      this.model.destroy();
      this.remove();
      return false;
    };

    UserView.prototype.render = function() {
      $(this.el).html(this.template(this.model.toJSON()));
      return this;
    };

    return UserView;

  })(Backbone.View);

}).call(this);
