// Generated by CoffeeScript 1.7.1
(function() {
  var _base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (_base = SuperCat.Views).Messages || (_base.Messages = {});

  SuperCat.Views.Messages.MessageView = (function(_super) {
    __extends(MessageView, _super);

    function MessageView() {
      return MessageView.__super__.constructor.apply(this, arguments);
    }

    MessageView.prototype.template = _.template(document.getElementById('message').innerHTML);

    MessageView.prototype.events = {
      "click .destroy": "destroy"
    };

    MessageView.prototype.tagName = "tr";

    MessageView.prototype.destroy = function() {
      this.model.destroy();
      this.remove();
      return false;
    };

    MessageView.prototype.render = function() {
      $(this.el).html(this.template(this.model.toJSON()));
      return this;
    };

    return MessageView;

  })(Backbone.View);

}).call(this);
