// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperCat.Routers.MessagesRouter = (function(_super) {
    __extends(MessagesRouter, _super);

    function MessagesRouter() {
      return MessagesRouter.__super__.constructor.apply(this, arguments);
    }

    MessagesRouter.prototype.initialize = function(options) {
      this.messages = new SuperCat.Collections.MessagesCollection();
      return this.messages.reset(options.messages);
    };

    MessagesRouter.prototype.routes = {
      "new": "newMessage",
      "index": "index",
      ":id/edit": "edit",
      ":id": "show",
      ".*": "index"
    };

    MessagesRouter.prototype.newMessage = function() {
      this.view = new SuperCat.Views.Messages.NewView({
        collection: this.messages
      });
      return $("#messages").html(this.view.render().el);
    };

    MessagesRouter.prototype.index = function() {
      this.view = new SuperCat.Views.Messages.IndexView({
        messages: this.messages
      });
      return $("#messages").html(this.view.render().el);
    };

    MessagesRouter.prototype.show = function(id) {
      var message;
      message = this.messages.get(id);
      this.view = new SuperCat.Views.Messages.ShowView({
        model: message
      });
      return $("#messages").html(this.view.render().el);
    };

    MessagesRouter.prototype.edit = function(id) {
      var message;
      message = this.messages.get(id);
      this.view = new SuperCat.Views.Messages.EditView({
        model: message
      });
      return $("#messages").html(this.view.render().el);
    };

    return MessagesRouter;

  })(Backbone.Router);

}).call(this);
