// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperCat.Routers.UsersRouter = (function(_super) {
    __extends(UsersRouter, _super);

    function UsersRouter() {
      return UsersRouter.__super__.constructor.apply(this, arguments);
    }

    UsersRouter.prototype.initialize = function(options) {
      this.users = new SuperCat.Collections.UsersCollection();
      return this.users.reset(options.users);
    };

    UsersRouter.prototype.routes = {
      "new": "newUser",
      "index": "index",
      ":id/edit": "edit",
      ":id": "show",
      ".*": "index"
    };

    UsersRouter.prototype.newUser = function() {
      this.view = new SuperCat.Views.Users.NewView({
        collection: this.users
      });
      return $("#users").html(this.view.render().el);
    };

    UsersRouter.prototype.index = function() {
      this.view = new SuperCat.Views.Users.IndexView({
        users: this.users
      });
      return $("#users").html(this.view.render().el);
    };

    UsersRouter.prototype.show = function(id) {
      var user;
      user = this.users.get(id);
      this.view = new SuperCat.Views.Users.ShowView({
        model: user
      });
      return $("#users").html(this.view.render().el);
    };

    UsersRouter.prototype.edit = function(id) {
      var user;
      user = this.users.get(id);
      this.view = new SuperCat.Views.Users.EditView({
        model: user
      });
      return $("#users").html(this.view.render().el);
    };

    return UsersRouter;

  })(Backbone.Router);

}).call(this);
