// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperCat.Models.Channel = (function(_super) {
    __extends(Channel, _super);

    function Channel() {
      return Channel.__super__.constructor.apply(this, arguments);
    }

    Channel.prototype.paramRoot = 'channel';

    Channel.prototype.defaults = {
      title: null,
      latitude: null,
      longitude: null,
      creator_id: null
    };

    return Channel;

  })(Backbone.Model);

  SuperCat.Collections.ChannelsCollection = (function(_super) {
    __extends(ChannelsCollection, _super);

    function ChannelsCollection() {
      return ChannelsCollection.__super__.constructor.apply(this, arguments);
    }

    ChannelsCollection.prototype.model = SuperCat.Models.Channel;

    ChannelsCollection.prototype.url = function() {
      return SuperCat.rootUrl + '/channels';
    };

    return ChannelsCollection;

  })(Backbone.Collection);

}).call(this);
