// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperCat.Models.User = (function(_super) {
    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.paramRoot = 'user';

    User.prototype.defaults = {
      email: null,
      message_zone: null,
      connected: null,
      latitude: null,
      longitude: null,
      pseudo: null,
      last_name: null,
      first_name: null,
      gender: null,
      birth_date: null,
      provider: null,
      uid: null,
      authentication_token: null
    };

    return User;

  })(Backbone.Model);

  SuperCat.Collections.UsersCollection = (function(_super) {
    __extends(UsersCollection, _super);

    function UsersCollection() {
      return UsersCollection.__super__.constructor.apply(this, arguments);
    }

    UsersCollection.prototype.model = SuperCat.Models.User;

    UsersCollection.prototype.url = function() {
      return SuperCat.rootUrl + '/users';
    };

    return UsersCollection;

  })(Backbone.Collection);

}).call(this);
